<?php

namespace ContentBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($id_page)
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder
            ->select('a.title, a.updatedAt, a.id, a.refUrl' )
            ->from('AppBundle:Article', 'a')
            ->where('a.page = :page ')
            ->setParameter('page', $id_page)
            ->andWhere('a.isActive = :active')
            ->setParameter('active', 1)
            ->add('orderBy', 'a.id ASC');

        return $queryBuilder->getQuery()->getResult();
    }

    public function getByRubrique($id_rubrique)
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder
            ->select('a.title, a.updatedAt, a.id, a.refUrl' )
            ->from('AppBundle:Article', 'a')
            ->innerJoin('a.page', 'p', 'WITH', 'a.page = p.id')
            ->where('p.rubrique = :rubrique ')
            ->setParameter('rubrique', $id_rubrique)
            ->andWhere('a.isActive = :active')
            ->setParameter('active', 1)
            ->add('orderBy', 'a.updatedAt ASC')
            ->setMaxResults(6);

        return $queryBuilder->getQuery()->getResult();
    }

    public function getByPageBlog()
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder
            ->select('p.id', 'p.title', 'p.descriptif', 'r.refUrl as rubRefUrl', 'r.id as rubId', 'count(a.id) as nbr_art')
            ->from('AppBundle:Article', 'a')
            ->innerJoin('a.page', 'p', 'WITH', 'p.id = a.page')
            ->innerJoin('p.rubrique', 'r', 'WITH', 'r.id = p.rubrique')
            ->where('p.rubrique = :rubrique ')
            ->setParameter('rubrique', 5)
            ->andWhere('p.isActive = :active')
            ->setParameter('active', 1)
            ->groupBy('a.page')
            ->add('orderBy', 'p.id ASC');

        return $queryBuilder->getQuery()->getResult();
    }
}
